### ISSUE TITLE
Kaiwa not navigating between views

### ISSUE THREAD

**Issue by maufl** [digicoop/kaiwa#37] opened 2015-06-28 19:51 UTC
I've been trying to run kaiwa for a while no, but I'm unsuccessful. Everything seems fine, I have it running, the client loads, I can log in and it even connects and recieves messages but the interface does not respond to any clicks. In the console I get the following error.
```
"Unhandled rejection [51]</</</<[38]</ensureErrorObject@http://chat.maufl.de/app.nonCached.js:15949:20
[51]</</</<[23]</module.exports/Promise.prototype._rejectCallback@http://chat.maufl.de/app.nonCached.js:13842:17
[51]</</</<[23]</module.exports/Promise.prototype._settlePromiseFromHandler@http://chat.maufl.de/app.nonCached.js:13886:9
[51]</</</<[23]</module.exports/Promise.prototype._settlePromiseAt@http://chat.maufl.de/app.nonCached.js:13956:13
[51]</</</<[23]</module.exports/Promise.prototype._settlePromises@http://chat.maufl.de/app.nonCached.js:14072:9
[51]</</</<[2]</Async.prototype._drainQueue@http://chat.maufl.de/app.nonCached.js:11439:13
[51]</</</<[2]</Async.prototype._drainQueues@http://chat.maufl.de/app.nonCached.js:11449:5
[51]</</</<[2]</Async/this.drainQueues@http://chat.maufl.de/app.nonCached.js:11279:9
"
```
I tried to debug it, and could trace the problem back to the async.series call in app.js. The last function is never called and the Backbone history is never started. Thus the app does not navigate anywhere, chat windows are not opened and the setting window is not opened.

When I put breakpoints into each function and manually continued the JavaScript, everything suddenly worked, so I guess it's a race condition of some sort.

I tested it in Firefox 38 and Chromium 43.

**Comment by lbischof** [comment] 2015-11-10 16:20
Did you find a fix for this? I am using the docker image and get the same error.

**Comment by Mynyx** [comment] 2015-12-16 22:53
The problem is an invalid muc in the config:

    "muc": "chat.example.com"

https://github.com/digicoop/kaiwa/blob/master/dev_config.example.json#L14

Replace it with:

    "muc": ""

**Closed** 2015-12-16 23:16 UTC
