### ISSUE TITLE
Remove LDAP user stuff

### ISSUE THREAD

**Issue by nils-werner** [digicoop/kaiwa#41] opened 2015-07-09 14:41 UTC
Most XMPP servers can prepopulate a roster from LDAP, so this is not the job of the client to do. Hence all LDAP stuff can be removed from kaiwa.

**Comment by andersruneson** [comment] 2015-07-21 17:50
Duplicate of #18

**Comment by sebu77** [comment] 2015-09-10 00:05
you can simply remove the "ldap":{}
The dependency has been removed

**Closed by sebu77** 2015-09-10 00:05 UTC
