### ISSUE TITLE
Cannot click anything

### ISSUE THREAD

**Issue by thmmueller** [digicoop/kaiwa#55] opened 2015-09-15 07:09 UTC
Hi all, 

I installed Kaiwa and could successfully connect it to our OpenFire server. Anyways, I'm not able to click anything after login. I can see the buddy list and if I click on any of them, nothing happens. Also the settings button is not clickable (I checked this, but it didn't help -> https://github.com/digicoop/kaiwa/issues/48), though I'm able to update status of user. 

I also checked traffic with tcpdump, when clicking any link in Kaiwa web client, but none of the requests arrived at server. 

When I send a message from a client (e.g. Pidgin), the user logged in on Kaiwa receives the message, but cannot open it, as nothing is clickable. 

I tried it with latest FF, latest Chrome and IE 11 on different workstations. 

Am I doing anything wrong? Could someone may please help me?

Greets
 Thomas

**Comment by andersruneson** [comment] 2015-09-15 07:11
Have you used the js console/dev tools in your browser? They may be able to
tell you more.

**Comment by thmmueller** [comment] 2015-09-15 07:22
Yes, I tried. I found this issue here, which exactly describes my problem -> https://www.bountysource.com/issues/23255732-kaiwa-not-navigating-between-views 

When adding the break points, it works. But I've no clue, how to fix it....

**Comment by sebu77** [comment] 2015-10-27 13:08
Duplicate of https://github.com/digicoop/kaiwa/issues/37

**Closed by sebu77** 2015-10-27 13:08 UTC
